name: Build and Deploy

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} Continuous Integration

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Validate Composer
        run: |
          composer validate

      - name: Install composer dependencies
        run: |
          composer install --optimize-autoloader --prefer-dist --no-progress --no-suggest
          composer dump-autoload

      - name: Install Dependencies
        run: npm install

      - name: Build Production
        run: npm run production

      - name: Create .nojekyll File
        run: |
          touch dist/.nojekyll

      - name: Move 'dist' to $RUNNER_TEMP
        run: |
          mv dist $RUNNER_TEMP
        working-directory: ${{ github.workspace }}

      - name: Config Git
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "aaftre@users.noreply.github.com"

      - name: Checkout gh-pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git clean -df

      - name: Move files back to current directory
        run: |
          for file in $RUNNER_TEMP/dist/*; do
            mv "$file" .
          done
        working-directory: ${{ github.workspace }}

      - name: Push to Github
        run: |
          git add .
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push -f origin gh-pages

      # - name: Setup Pages
      #   uses: actions/configure-pages@v3

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     path: 'dist/'
      
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v2