name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} Continuous Integration

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.blog.aftre.net/gh-pages }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Validate Composer
        run: |
          composer validate

      - name: Install composer dependencies
        run: |
          composer install --optimize-autoloader --prefer-dist --no-progress --no-suggest
          composer dump-autoload

      - name: Install Dependencies
        run: npm install

      - name: Build Production
        run: npm run production

      - name: Config Git
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "aaftre@users.noreply.github.com"

      - name: Checkout gh-pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard

      - name: Push to Github
        run: |
          git add dist
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git clean -df
          git push -f origin gh-pages
