name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      # - name: Create Directory for GitHub Pages
      #   run: mkdir gh-pages

      # - name: Copy Artifacts to GitHub Pages Directory
      #   run: cp -r dist/* gh-pages/ # Replace path/to/artifacts with the actual path

      - name: Config Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout gh-pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git clean -df

      - name: Install Dependencies
        run: npm install

      - name: Build Production
        run: npm run production

      - name: Push to Github
        run: |
          git add .
          git commit -m "Publish artifacts to GitHub Pages"
          git push -f origin gh-pages
